# Generated by Django 5.1.2 on 2024-10-10 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='title1',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='title2',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='title3',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='title4',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='title5',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='title6',
        ),
    ]
