# Generated by Django 5.1.2 on 2024-10-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course_app', '0002_remove_topic_title1_remove_topic_title2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicdetail',
            name='url',
            field=models.URLField(default='', max_length=250),
        ),
    ]
