# Generated by Django 5.1.2 on 2024-10-11 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course_app', '0003_topicdetail_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicdetail',
            name='code_t1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='topicdetail',
            name='code_t2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='topicdetail',
            name='code_t3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='topicdetail',
            name='code_t4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='topicdetail',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='topicdetail',
            name='content_t1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='topicdetail',
            name='content_t2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='topicdetail',
            name='content_t3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='topicdetail',
            name='content_t4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='topicdetail',
            name='t1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='topicdetail',
            name='t2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='topicdetail',
            name='t3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='topicdetail',
            name='t4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='topicdetail',
            name='url',
            field=models.URLField(blank=True, default='', max_length=250, null=True),
        ),
    ]
